- src/pb-paginate.js
* make bullet of active page *always* round, independently from
font-size or font-family instead of oval
* replace static values with global variables
> fix(pb-paginate): Fix css

- demo/demos.json
- demo/pb-autocomplete.html
- demo/pb-autocomplete2.html
- demo/pb-browse-docs2.html
- demo/pb-search2.html
- demo/pb-select-i18n.html
- demo/pb-select.html
- demo/pb-select2.html
- demo/pb-select3.html
- src/pb-autocomplete.js
- src/pb-i18n.js
- src/pb-page.js
- src/pb-select.js
- src/pb-view.js
- test/pb-autocomplete.test.js
- test/pb-i18n.test.js
- test/pb-select.test.js
`pb-page` sends a `pb-i18n-update` event when translations become available. This event was used to set the singleton translation function for the lit-html parts as well as trigger `pb-i18n` to update. However, the latter requires that the translation function is already set, and because there is no guarantee in which sequence event listeners are processed, the function may still have been undefined when the event reached `pb-i18n`. Solution: `pb-page` now explicitely sets the translation function singleton **before** it triggers the event. This way - whoever receives the event next - can be sure there's a translation function already set.
The PR also addresses an issue with `pb-i18n` translations being used in the options passed to `pb-select`: `paper-dropdown-menu` uses the text content …
> fix(pb-i18n): fix concurrency issue

- src/pb-search.js
enforced usage of pb-mixin.getParameters() in form submit / _doSearch()
> fix(pb-search) - fixed _doSearch()

- demo/pb-search3.html
- demo/pb-search4.html
- src/pb-search.js
- src/pb-select.js
support slots for 'search' and 'reset' controls.
This allows to create a pb-search:
* without any buttons (default)
* with native buttons
* with paper-buttons
* other elements that support the 'click' event.
Demo file (pb-search4.html) included
> feat(pb-search) slots for 'search' + 'reset' controls

- demo/pb-search3.html
- src/pb-select.js
without default size multi selects will take huge space. Can be overwritten by user.
New demo file shows multi select with scrolling
> fix(pb-select) default sizing for multi

- src/pb-search.js
search and reset buttons can be slotted but attaching listeners to the slots did work only in the demo but not in context of Publisher app.
Now using a bubbling listener on the parent (pb-search itself) with target detection. This has been tested in both scenarios.
> fix(pb-search) fixing search/reset handler

- demo/pb-search3.html
- src/pb-browse-docs.js
- src/pb-custom-form.js
- src/pb-load.js
- src/pb-search.js
from pb-custom-form elements located elsewhere on the page.
Adds a property `subforms` to `pb-search`, containing a CSS selector.
> Make pb-search collect form data

- src/authority/connectors.js
- src/authority/reconciliation.js
API spec: https://reconciliation-api.github.io/specs/latest/
W3C Community Group: https://www.w3.org/community/reconciliation/ (Some of them are the same people who run lobid at HBZ NRW)
The API is based on OpenRefine's reconciliation function and provides some additional functions such as type-ahead suggestions and more. There is a list of platforms who run a Reconciliation Service API endpoint at https://reconciliation-api.github.io/testbench/.
The Reconciliation Service connector can be used like this:
`<pb-authority connector="ReconciliationService" name="term" prefix="wd" endpoint="https://wikidata.reconci.link/api" debug="debug"/>`
In other words, you define the `endpoint` and a `prefix` and that's it. The `debug` switch gives diagnostic output in the browser console and can be left …
> Add Reconciliation Service authority connector (2d try)

- src/pb-repeat.js
See issue #29.
Name property is not available (defined), but can be reached as the attribute value.
> undefined name property in pb-repeat fixed

- i18n/common/en.json
- src/pb-ajax.js
- src/pb-browse.js
- src/pb-components.js
- src/pb-message.js
- test/pb-ajax.test.js
The component used for browsing collections on TEI Publisher's start page, `pb-browse-docs`, has a number of problems. Most important, it includes user interface components in the shadow DOM, which are thus not customizable.
`pb-browse` is a replacement, dropping all UI components and most of the functionality. Instead it is just a thin wrapper on top of the generic `pb-load`. This makes it possible to combine the component more freely with other components and implement different types of views on a collection.
> Refactor pb-browse-docs

- package.json
- src/pb-facsimile.js
…view
After user opened pb-facsimile in full screen popups in the text broke as their eventlisteners got lost. This fix requires a patched OSD version and the package.json will pull from the github fork.
This patch assumes that pb-facsimile will live inside of a `pb-page` element which takes the viewport. 
Can be further generified but requires more work.
> Pb facsimile fullscreen

- demo/demos.json
- demo/pb-image-strip-standalone.html
- demo/pb-image-strip-view.html
- src/pb-components.js
- src/pb-facs-link.js
- src/pb-facsimile.js
- src/pb-image-strip.js
refs #85 
Needs testing with real applications as it modifies pb-facs-link behaviour
TODO:
> new component pb-image-strip

- .gitattributes
- .gitignore
feat(line-endings): configure git to always use LF on server and allow client-specific handling.
This just fell onto my feet trying to make a PR for pb-collapse which had CRLF line endings. To correct linter warning i used LF leaving me with a unusable diff with a lines being changed. 
To fix the issue with people using different platforms git is configured to always use LF in repo but adopt for user workspaces - see https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/
> Line endings

- demo/pb-collapse.html
- src/pb-collapse.js
feat(pb-collapse): icon can be positioned on the right by adding a CSS class 'icon-right'
When using e.g. in mobile menus it can be desirable to put the icon on the right side. E.g TEI-Publisher index page.
Apologies for the broken diff - couldn't find a way to commit CRLF from my machine and line-endings should be LF in the repo anyway but it is CRLF on master. If that's not acceptable we probably have to fix it on master before.
My other PR (line-endings) should fix that problem for the future. Not sure but probably can even resolve this PR when applied before.
The actual changes are just 2 CSS additions:
```
:host {
display: block;
>>>                position: relative;
}
```
and ```
:host(.icon-right) iron-icon {
position: absolute;
right: 0;
}
```
> Pb collapse right

- src/pb-search.js
Optional URL to query for suggestions. for example from custom API endpoint.
If not set, api/search/autocomplete API endpoint, or /modules/autocomplete.xql module is used.
> Optional URL to query for suggestions

- src/pb-manage-odds.js
* add titles for all links
* add explicit icon for editing odd in editor
* showing icons only on hover when the device supports hover and a mouse
* refined spacing to work responsively
> feat(pb-manage-odds): layout and a11y refinements

- src/pb-split-list.js
fixed error in pb-split-list if map in category contains a label like:
```
map {
"category": "[A-Z]",
"count": count($sorted),
"label": "Alle"
}
```
Without this patch an error `Uncaught (in promise) ReferenceError: unsafeHTML is not defined` will be thrown.
> fix(pb-split-list): added missing import

- src/pb-code-highlight.js
When the `code` property is changed programmatically from JavaScript, the content of the element is replaced with the new code and highlighted.
The previous implementation did not change the content of the element.
> Change the content of the component if the code property is changed

- src/pb-navigation.js
With new `rendition` attribute user can set is how the disabled control (button) rendered. 
In the previous and now in the default implementation, the control is removed from the document layout. 
With `rendition` attribute user can set two new options
- controll is hidden, but keeped in the document layout
- control is allways visible
These options prevent the user interface layout from changing.
> Controlling the rendering of a disabled navigation control

- src/pb-highlight.js
- Changes default vertical alignment of property `scroll` (center instead of top). This way the user can read the preceding context.
- When `<pb-highlight>` was disabled, the element was still scrolled into view: this has been fixed.
> Minor changes in pb-highlight concerning `scroll` property

- src/pb-collapse.js
The use of `display:flex` in the `<pb-collapse>` `#trigger` was causing readjustments of the size of the icons. See:
This PR proposes using `grid` instead of `flex` to avoid these changes.
> change of width in pb-collapase icons

- src/pb-view-annotate.js
In the annotation view, inserted `<pb>` and `<note>` elements are placed before the selected text.
The proposed change, combined with changes on the TEI Publisher side, allows the user to choose where the inserted element will be placed by specifying 'after' or 'before' value in the  `@class` attribute of the button for the annotation element.
See parallel required [pull request](https://github.com/eeditiones/tei-publisher-app/pull/232) in the TEI Publisher.
> Allow placing the annotation element after the selected text

- src/pb-combo-box.js
This PR addresses an issue where `tom-select` appends new items fetched from the server to the existing list, instead of replacing them (see https://github.com/eeditiones/tei-publisher-components/issues/189). While this behavior makes sense when using tom-select's client-side search functionality, the primary use case for `pb-combo-box` is probably to have the server determine which items to display. To align with this use case, the items should be cleared before refetching new data from the server.
Additionally, I changed the type of the `preload` property from `Boolean` to `String`. `tom-select` supports setting that property to the string `focus`, which triggers loading data when the control is focused. This change allows `pb-combo-box` to display items even if no search term has been …
> fix(pb-combo-box): Clear items before refetching (fixes #189)

- src/pb-formula.js
LaTex code within the `<tei:formula>` element presents the XML entities which need to be replaced before typesetting the formula.
E.g. of current display:
```
<formula> \begin{array}{c@{\hspace{1em}}c} 1 &amp; 2 \\ 3 &amp; 4 \end{array} </formula>
```
> fix(pb-formula): replace XML entities

- src/pb-tify.js
This PR adds support for the `coordinates` attribute sent by `pb-facs-link` or the `pb-show-annotation` event to `pb-tify`.
While implementing this, I noticed that triggering `pb-show-annotation` twice with the same `order` attribute caused the Tify viewer to flicker. To resolve this, I added a safeguard to ignore navigating to the already active page.
Example in our project:
https://github.com/user-attachments/assets/5a29d1c3-4378-4e07-8664-db5d0ecb700e
> Support for rectangle highlighting in `pb-tify`
